// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class AiRecommendation
{
    public long Id { get; set; }

    public long BriefId { get; set; }

    public string ConceptSummary { get; set; }

    public string Payload { get; set; }

    public decimal? EstimatedDesignCost { get; set; }

    public decimal? EstimatedConstructionCost { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual DesignBrief Brief { get; set; }
}