// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Approval
{
    public long Id { get; set; }

    public long? DesignVersionId { get; set; }

    public long? ProgressUpdateId { get; set; }

    public long OwnerId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<ApprovalHistory> ApprovalHistories { get; set; } = new List<ApprovalHistory>();

    public virtual DesignVersion DesignVersion { get; set; }

    public virtual OwnerProfile Owner { get; set; }

    public virtual ProgressUpdate ProgressUpdate { get; set; }
}