// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class ApprovalHistory
{
    public long Id { get; set; }

    public long ApprovalId { get; set; }

    public string FromStatus { get; set; }

    public string ToStatus { get; set; }

    public long ChangedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Approval Approval { get; set; }

    public virtual User ChangedByNavigation { get; set; }
}