// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Attachment
{
    public long Id { get; set; }

    public string OwnerType { get; set; }

    public long OwnerId { get; set; }

    public string FileUrl { get; set; }

    public string FileName { get; set; }

    public string Caption { get; set; }

    public string DocType { get; set; }

    public long? UploadedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User UploadedByNavigation { get; set; }
}