// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Bid
{
    public long Id { get; set; }

    public long BidRequestId { get; set; }

    public long ProviderId { get; set; }

    public decimal BidAmount { get; set; }

    public string Proposal { get; set; }

    public int? EstimatedDurationDays { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual BidRequest BidRequest { get; set; }

    public virtual ICollection<ProjectHire> ProjectHires { get; set; } = new List<ProjectHire>();

    public virtual ServiceProvider Provider { get; set; }
}