// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class BidRequest
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long ServiceTypeId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal? EstimatedBudget { get; set; }

    public DateTime? SubmissionDeadline { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Bid> Bids { get; set; } = new List<Bid>();

    public virtual Project Project { get; set; }

    public virtual ServiceType ServiceType { get; set; }
}