// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class BudgetItem
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public string Category { get; set; }

    public decimal PlannedAmount { get; set; }

    public decimal? ActualAmount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Project Project { get; set; }
}