// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class ConstructorProfile
{
    public long Id { get; set; }

    public long ProviderId { get; set; }

    public string LicenseNo { get; set; }

    public int? TeamSize { get; set; }

    public string Equipment { get; set; }

    public decimal? MaxProjectValue { get; set; }

    public string WarrantyPolicy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ServiceProvider Provider { get; set; }
}