// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Contract
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long HireId { get; set; }

    public string Title { get; set; }

    public string PartyInfo { get; set; }

    public string Terms { get; set; }

    public decimal? AgreedValue { get; set; }

    public string DocumentUrl { get; set; }

    public string OtpCode { get; set; }

    public DateTime? OtpExpiresAt { get; set; }

    public DateTime? ConfirmedAt { get; set; }

    public long? ConfirmedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User ConfirmedByNavigation { get; set; }

    public virtual ICollection<Handover> Handovers { get; set; } = new List<Handover>();

    public virtual ProjectHire Hire { get; set; }

    public virtual Project Project { get; set; }
}