// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Conversation
{
    public long Id { get; set; }

    public long? ProjectId { get; set; }

    public string Topic { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ConversationMember> ConversationMembers { get; set; } = new List<ConversationMember>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual Project Project { get; set; }
}