// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Design
{
    public long Id { get; set; }

    public long HireId { get; set; }

    public string Title { get; set; }

    public long? CurrentVersionId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual DesignVersion CurrentVersion { get; set; }

    public virtual ICollection<DesignVersion> DesignVersions { get; set; } = new List<DesignVersion>();

    public virtual ProjectHire Hire { get; set; }
}