// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class DesignerProfile
{
    public long Id { get; set; }

    public long ProviderId { get; set; }

    public string DesignSpecialties { get; set; }

    public string SoftwareSkills { get; set; }

    public string DesignStyle { get; set; }

    public decimal? MinProjectBudget { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ServiceProvider Provider { get; set; }
}