// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class DesignVersion
{
    public long Id { get; set; }

    public long DesignId { get; set; }

    public int VersionNo { get; set; }

    public string FileUrl { get; set; }

    public string Note { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Approval> Approvals { get; set; } = new List<Approval>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual Design Design { get; set; }

    public virtual ICollection<Design> Designs { get; set; } = new List<Design>();
}