// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class DesignBrief
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public string TargetCustomer { get; set; }

    public string Style { get; set; }

    public string Mood { get; set; }

    public int? SeatCount { get; set; }

    public string OperationNote { get; set; }

    public string BrandNote { get; set; }

    public string Timeline { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AiRecommendation> AiRecommendations { get; set; } = new List<AiRecommendation>();

    public virtual Project Project { get; set; }
}