// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Handover
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long? ContractId { get; set; }

    public DateOnly HandoverDate { get; set; }

    public string DocumentUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<Warranty> Warranties { get; set; } = new List<Warranty>();
}