// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Inspection
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long? HireId { get; set; }

    public DateTime? InspectedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ProjectHire Hire { get; set; }

    public virtual ICollection<InspectionItem> InspectionItems { get; set; } = new List<InspectionItem>();

    public virtual Project Project { get; set; }
}