// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class InspectionItem
{
    public long Id { get; set; }

    public long InspectionId { get; set; }

    public string Description { get; set; }

    public bool IsPassed { get; set; }

    public string DefectNote { get; set; }

    public virtual Inspection Inspection { get; set; }
}