// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Issue
{
    public long Id { get; set; }

    public long HireId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public decimal? CostImpact { get; set; }

    public int? ScheduleImpactDays { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProjectHire Hire { get; set; }
}