// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Message
{
    public long Id { get; set; }

    public long ConversationId { get; set; }

    public long SenderId { get; set; }

    public string Body { get; set; }

    public DateTime SentAt { get; set; }

    public virtual Conversation Conversation { get; set; }

    public virtual User Sender { get; set; }
}