// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Permission
{
    public long Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}