// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Project
{
    public long Id { get; set; }

    public long OwnerId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public decimal? AreaM2 { get; set; }

    public decimal? Budget { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<BidRequest> BidRequests { get; set; } = new List<BidRequest>();

    public virtual ICollection<BudgetItem> BudgetItems { get; set; } = new List<BudgetItem>();

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();

    public virtual DesignBrief DesignBrief { get; set; }

    public virtual Handover Handover { get; set; }

    public virtual ICollection<Inspection> Inspections { get; set; } = new List<Inspection>();

    public virtual OwnerProfile Owner { get; set; }

    public virtual ICollection<ProjectHire> ProjectHires { get; set; } = new List<ProjectHire>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}