// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class ProjectHire
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long ProviderId { get; set; }

    public long ServiceTypeId { get; set; }

    public long? BidId { get; set; }

    public string RequestMessage { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Bid Bid { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual ICollection<Design> Designs { get; set; } = new List<Design>();

    public virtual ICollection<Inspection> Inspections { get; set; } = new List<Inspection>();

    public virtual ICollection<Issue> Issues { get; set; } = new List<Issue>();

    public virtual ICollection<ProgressUpdate> ProgressUpdates { get; set; } = new List<ProgressUpdate>();

    public virtual Project Project { get; set; }

    public virtual ServiceProvider Provider { get; set; }

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual ServiceType ServiceType { get; set; }

    public virtual ICollection<Survey> Surveys { get; set; } = new List<Survey>();
}