// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class ProviderService
{
    public long ProviderId { get; set; }

    public long ServiceTypeId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ServiceProvider Provider { get; set; }

    public virtual ServiceType ServiceType { get; set; }
}