// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class QuotationItem
{
    public long Id { get; set; }

    public long QuotationId { get; set; }

    public string Description { get; set; }

    public decimal Quantity { get; set; }

    public string Unit { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal LineTotal { get; set; }

    public virtual Quotation Quotation { get; set; }
}