// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Quotation
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long? HireId { get; set; }

    public long ProviderId { get; set; }

    public decimal TotalAmount { get; set; }

    public DateOnly? ValidUntil { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProjectHire Hire { get; set; }

    public virtual Project Project { get; set; }

    public virtual ServiceProvider Provider { get; set; }

    public virtual ICollection<QuotationItem> QuotationItems { get; set; } = new List<QuotationItem>();
}