// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class ReviewScore
{
    public long Id { get; set; }

    public long ReviewId { get; set; }

    public string Dimension { get; set; }

    public int Score { get; set; }

    public virtual Review Review { get; set; }
}