// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Review
{
    public long Id { get; set; }

    public long ProjectId { get; set; }

    public long ProviderId { get; set; }

    public long OwnerId { get; set; }

    public decimal OverallRating { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual OwnerProfile Owner { get; set; }

    public virtual Project Project { get; set; }

    public virtual ServiceProvider Provider { get; set; }

    public virtual ICollection<ReviewScore> ReviewScores { get; set; } = new List<ReviewScore>();
}