// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class ServiceProvider
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string DisplayName { get; set; }

    public string CompanyTaxCode { get; set; }

    public string Bio { get; set; }

    public string PortfolioHeadline { get; set; }

    public int? YearsExperience { get; set; }

    public bool IsVerified { get; set; }

    public decimal? AvgRating { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<Bid> Bids { get; set; } = new List<Bid>();

    public virtual ConstructorProfile ConstructorProfile { get; set; }

    public virtual DesignerProfile DesignerProfile { get; set; }

    public virtual ICollection<PortfolioItem> PortfolioItems { get; set; } = new List<PortfolioItem>();

    public virtual ICollection<ProjectHire> ProjectHires { get; set; } = new List<ProjectHire>();

    public virtual ICollection<ProviderService> ProviderServices { get; set; } = new List<ProviderService>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual User User { get; set; }
}