// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class ServiceType
{
    public long Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BidRequest> BidRequests { get; set; } = new List<BidRequest>();

    public virtual ICollection<PortfolioItem> PortfolioItems { get; set; } = new List<PortfolioItem>();

    public virtual ICollection<ProjectHire> ProjectHires { get; set; } = new List<ProjectHire>();

    public virtual ICollection<ProviderService> ProviderServices { get; set; } = new List<ProviderService>();
}