// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class SmartCafeBuilderContext : DbContext
{
    public SmartCafeBuilderContext(DbContextOptions<SmartCafeBuilderContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AiRecommendation> AiRecommendations { get; set; }

    public virtual DbSet<Approval> Approvals { get; set; }

    public virtual DbSet<ApprovalHistory> ApprovalHistories { get; set; }

    public virtual DbSet<Attachment> Attachments { get; set; }

    public virtual DbSet<Bid> Bids { get; set; }

    public virtual DbSet<BidRequest> BidRequests { get; set; }

    public virtual DbSet<BudgetItem> BudgetItems { get; set; }

    public virtual DbSet<ConstructorProfile> ConstructorProfiles { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<Conversation> Conversations { get; set; }

    public virtual DbSet<ConversationMember> ConversationMembers { get; set; }

    public virtual DbSet<Design> Designs { get; set; }

    public virtual DbSet<DesignBrief> DesignBriefs { get; set; }

    public virtual DbSet<DesignVersion> DesignVersions { get; set; }

    public virtual DbSet<DesignerProfile> DesignerProfiles { get; set; }

    public virtual DbSet<Handover> Handovers { get; set; }

    public virtual DbSet<HelpContent> HelpContents { get; set; }

    public virtual DbSet<Inspection> Inspections { get; set; }

    public virtual DbSet<InspectionItem> InspectionItems { get; set; }

    public virtual DbSet<Issue> Issues { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<OwnerProfile> OwnerProfiles { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<PlatformFee> PlatformFees { get; set; }

    public virtual DbSet<PortfolioItem> PortfolioItems { get; set; }

    public virtual DbSet<ProgressUpdate> ProgressUpdates { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectHire> ProjectHires { get; set; }

    public virtual DbSet<ProviderService> ProviderServices { get; set; }

    public virtual DbSet<Quotation> Quotations { get; set; }

    public virtual DbSet<QuotationItem> QuotationItems { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<ReviewScore> ReviewScores { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }

    public virtual DbSet<ServiceType> ServiceTypes { get; set; }

    public virtual DbSet<Survey> Surveys { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<Warranty> Warranties { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("approval_status", new[] { "pending", "approved", "rejected", "revision_requested" })
            .HasPostgresEnum("approval_type", new[] { "design", "construction" })
            .HasPostgresEnum("bid_request_status", new[] { "open", "closed", "awarded", "cancelled" })
            .HasPostgresEnum("bid_status", new[] { "submitted", "shortlisted", "won", "lost", "withdrawn" })
            .HasPostgresEnum("contract_status", new[] { "draft", "pending_otp", "confirmed", "cancelled" })
            .HasPostgresEnum("design_type", new[] { "concept", "layout_2d", "render_3d", "technical_drawing" })
            .HasPostgresEnum("fee_type", new[] { "percentage", "fixed" })
            .HasPostgresEnum("help_content_type", new[] { "checklist", "guideline", "support" })
            .HasPostgresEnum("hire_status", new[] { "requested", "accepted", "rejected", "in_progress", "completed", "terminated" })
            .HasPostgresEnum("inspection_result", new[] { "pass", "fail", "conditional" })
            .HasPostgresEnum("inspection_type", new[] { "partial", "final" })
            .HasPostgresEnum("issue_severity", new[] { "low", "medium", "high", "critical" })
            .HasPostgresEnum("issue_status", new[] { "open", "in_progress", "resolved" })
            .HasPostgresEnum("project_status", new[] { "draft", "briefing", "designing", "quoting", "contracted", "constructing", "inspection", "completed", "cancelled" })
            .HasPostgresEnum("provider_type", new[] { "individual", "company" })
            .HasPostgresEnum("quotation_status", new[] { "draft", "sent", "clarifying", "accepted", "rejected" })
            .HasPostgresEnum("user_status", new[] { "active", "inactive", "banned", "pending" })
            .HasPostgresExtension("google_vacuum_mgmt", "google_vacuum_mgmt");

        modelBuilder.Entity<AiRecommendation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ai_recommendations_pkey");

            entity.ToTable("ai_recommendations");

            entity.HasIndex(e => e.BriefId, "idx_ai_recos_brief");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.BriefId).HasColumnName("brief_id");
            entity.Property(e => e.ConceptSummary).HasColumnName("concept_summary");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.EstimatedConstructionCost)
                .HasPrecision(15, 2)
                .HasColumnName("estimated_construction_cost");
            entity.Property(e => e.EstimatedDesignCost)
                .HasPrecision(15, 2)
                .HasColumnName("estimated_design_cost");
            entity.Property(e => e.Payload)
                .HasColumnType("jsonb")
                .HasColumnName("payload");

            entity.HasOne(d => d.Brief).WithMany(p => p.AiRecommendations)
                .HasForeignKey(d => d.BriefId)
                .HasConstraintName("ai_recommendations_brief_id_fkey");
        });

        modelBuilder.Entity<Approval>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("approvals_pkey");

            entity.ToTable("approvals");

            entity.HasIndex(e => e.DesignVersionId, "idx_approvals_dv");

            entity.HasIndex(e => e.OwnerId, "idx_approvals_owner");

            entity.HasIndex(e => e.ProgressUpdateId, "idx_approvals_pu");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DesignVersionId).HasColumnName("design_version_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.ProgressUpdateId).HasColumnName("progress_update_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.DesignVersion).WithMany(p => p.Approvals)
                .HasForeignKey(d => d.DesignVersionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("approvals_design_version_id_fkey");

            entity.HasOne(d => d.Owner).WithMany(p => p.Approvals)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("approvals_owner_id_fkey");

            entity.HasOne(d => d.ProgressUpdate).WithMany(p => p.Approvals)
                .HasForeignKey(d => d.ProgressUpdateId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("approvals_progress_update_id_fkey");
        });

        modelBuilder.Entity<ApprovalHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("approval_history_pkey");

            entity.ToTable("approval_history");

            entity.HasIndex(e => e.ApprovalId, "idx_approval_history_approval");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.ApprovalId).HasColumnName("approval_id");
            entity.Property(e => e.ChangedBy).HasColumnName("changed_by");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.FromStatus)
                .HasMaxLength(30)
                .HasColumnName("from_status");
            entity.Property(e => e.ToStatus)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("to_status");

            entity.HasOne(d => d.Approval).WithMany(p => p.ApprovalHistories)
                .HasForeignKey(d => d.ApprovalId)
                .HasConstraintName("approval_history_approval_id_fkey");

            entity.HasOne(d => d.ChangedByNavigation).WithMany(p => p.ApprovalHistories)
                .HasForeignKey(d => d.ChangedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("approval_history_changed_by_fkey");
        });

        modelBuilder.Entity<Attachment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("attachments_pkey");

            entity.ToTable("attachments");

            entity.HasIndex(e => new { e.OwnerType, e.OwnerId }, "idx_attachments_owner");

            entity.HasIndex(e => e.UploadedBy, "idx_attachments_uploader");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Caption)
                .HasMaxLength(255)
                .HasColumnName("caption");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DocType)
                .HasMaxLength(50)
                .HasColumnName("doc_type");
            entity.Property(e => e.FileName)
                .HasMaxLength(200)
                .HasColumnName("file_name");
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("file_url");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.OwnerType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("owner_type");
            entity.Property(e => e.UploadedBy).HasColumnName("uploaded_by");

            entity.HasOne(d => d.UploadedByNavigation).WithMany(p => p.Attachments)
                .HasForeignKey(d => d.UploadedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("attachments_uploaded_by_fkey");
        });

        modelBuilder.Entity<Bid>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("bids_pkey");

            entity.ToTable("bids");

            entity.HasIndex(e => e.ProviderId, "idx_bids_provider");

            entity.HasIndex(e => e.BidRequestId, "idx_bids_request");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.BidAmount)
                .HasPrecision(15, 2)
                .HasColumnName("bid_amount");
            entity.Property(e => e.BidRequestId).HasColumnName("bid_request_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.EstimatedDurationDays).HasColumnName("estimated_duration_days");
            entity.Property(e => e.Proposal).HasColumnName("proposal");
            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.SubmittedAt).HasColumnName("submitted_at");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.BidRequest).WithMany(p => p.Bids)
                .HasForeignKey(d => d.BidRequestId)
                .HasConstraintName("bids_bid_request_id_fkey");

            entity.HasOne(d => d.Provider).WithMany(p => p.Bids)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("bids_provider_id_fkey");
        });

        modelBuilder.Entity<BidRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("bid_requests_pkey");

            entity.ToTable("bid_requests");

            entity.HasIndex(e => e.ProjectId, "idx_bid_requests_project");

            entity.HasIndex(e => e.ServiceTypeId, "idx_bid_requests_type");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EstimatedBudget)
                .HasPrecision(15, 2)
                .HasColumnName("estimated_budget");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.ServiceTypeId).HasColumnName("service_type_id");
            entity.Property(e => e.SubmissionDeadline).HasColumnName("submission_deadline");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Project).WithMany(p => p.BidRequests)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("bid_requests_project_id_fkey");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.BidRequests)
                .HasForeignKey(d => d.ServiceTypeId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("bid_requests_service_type_id_fkey");
        });

        modelBuilder.Entity<BudgetItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("budget_items_pkey");

            entity.ToTable("budget_items");

            entity.HasIndex(e => e.ProjectId, "idx_budget_items_project");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.ActualAmount)
                .HasPrecision(15, 2)
                .HasColumnName("actual_amount");
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("category");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.PlannedAmount)
                .HasPrecision(15, 2)
                .HasColumnName("planned_amount");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Project).WithMany(p => p.BudgetItems)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("budget_items_project_id_fkey");
        });

        modelBuilder.Entity<ConstructorProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("constructor_profiles_pkey");

            entity.ToTable("constructor_profiles");

            entity.HasIndex(e => e.ProviderId, "constructor_profiles_provider_id_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Equipment)
                .HasMaxLength(255)
                .HasColumnName("equipment");
            entity.Property(e => e.LicenseNo)
                .HasMaxLength(100)
                .HasColumnName("license_no");
            entity.Property(e => e.MaxProjectValue)
                .HasPrecision(15, 2)
                .HasColumnName("max_project_value");
            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.TeamSize).HasColumnName("team_size");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.WarrantyPolicy)
                .HasMaxLength(255)
                .HasColumnName("warranty_policy");

            entity.HasOne(d => d.Provider).WithOne(p => p.ConstructorProfile)
                .HasForeignKey<ConstructorProfile>(d => d.ProviderId)
                .HasConstraintName("constructor_profiles_provider_id_fkey");
        });

        modelBuilder.Entity<Contract>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("contracts_pkey");

            entity.ToTable("contracts");

            entity.HasIndex(e => e.HireId, "idx_contracts_hire");

            entity.HasIndex(e => e.ProjectId, "idx_contracts_project");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.AgreedValue)
                .HasPrecision(15, 2)
                .HasColumnName("agreed_value");
            entity.Property(e => e.ConfirmedAt).HasColumnName("confirmed_at");
            entity.Property(e => e.ConfirmedBy).HasColumnName("confirmed_by");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentUrl)
                .HasMaxLength(500)
                .HasColumnName("document_url");
            entity.Property(e => e.HireId).HasColumnName("hire_id");
            entity.Property(e => e.OtpCode)
                .HasMaxLength(10)
                .HasColumnName("otp_code");
            entity.Property(e => e.OtpExpiresAt).HasColumnName("otp_expires_at");
            entity.Property(e => e.PartyInfo).HasColumnName("party_info");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.Terms).HasColumnName("terms");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.ConfirmedByNavigation).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.ConfirmedBy)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("contracts_confirmed_by_fkey");

            entity.HasOne(d => d.Hire).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.HireId)
                .HasConstraintName("contracts_hire_id_fkey");

            entity.HasOne(d => d.Project).WithMany(p => p.Contracts)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("contracts_project_id_fkey");
        });

        modelBuilder.Entity<Conversation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("conversations_pkey");

            entity.ToTable("conversations");

            entity.HasIndex(e => e.ProjectId, "idx_conversations_project");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.Topic)
                .HasMaxLength(200)
                .HasColumnName("topic");

            entity.HasOne(d => d.Project).WithMany(p => p.Conversations)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("conversations_project_id_fkey");
        });

        modelBuilder.Entity<ConversationMember>(entity =>
        {
            entity.HasKey(e => new { e.ConversationId, e.UserId }).HasName("conversation_members_pkey");

            entity.ToTable("conversation_members");

            entity.HasIndex(e => e.UserId, "idx_conv_members_user");

            entity.Property(e => e.ConversationId).HasColumnName("conversation_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("joined_at");

            entity.HasOne(d => d.Conversation).WithMany(p => p.ConversationMembers)
                .HasForeignKey(d => d.ConversationId)
                .HasConstraintName("conversation_members_conversation_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.ConversationMembers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("conversation_members_user_id_fkey");
        });

        modelBuilder.Entity<Design>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("designs_pkey");

            entity.ToTable("designs");

            entity.HasIndex(e => e.HireId, "idx_designs_hire");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CurrentVersionId).HasColumnName("current_version_id");
            entity.Property(e => e.HireId).HasColumnName("hire_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CurrentVersion).WithMany(p => p.Designs)
                .HasForeignKey(d => d.CurrentVersionId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_designs_current_version");

            entity.HasOne(d => d.Hire).WithMany(p => p.Designs)
                .HasForeignKey(d => d.HireId)
                .HasConstraintName("designs_hire_id_fkey");
        });

        modelBuilder.Entity<DesignBrief>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("design_briefs_pkey");

            entity.ToTable("design_briefs");

            entity.HasIndex(e => e.ProjectId, "design_briefs_project_id_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.BrandNote).HasColumnName("brand_note");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Mood)
                .HasMaxLength(100)
                .HasColumnName("mood");
            entity.Property(e => e.OperationNote).HasColumnName("operation_note");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.SeatCount).HasColumnName("seat_count");
            entity.Property(e => e.Style)
                .HasMaxLength(100)
                .HasColumnName("style");
            entity.Property(e => e.TargetCustomer)
                .HasMaxLength(255)
                .HasColumnName("target_customer");
            entity.Property(e => e.Timeline)
                .HasMaxLength(100)
                .HasColumnName("timeline");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Project).WithOne(p => p.DesignBrief)
                .HasForeignKey<DesignBrief>(d => d.ProjectId)
                .HasConstraintName("design_briefs_project_id_fkey");
        });

        modelBuilder.Entity<DesignVersion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("design_versions_pkey");

            entity.ToTable("design_versions");

            entity.HasIndex(e => e.CreatedBy, "idx_design_versions_creator");

            entity.HasIndex(e => e.DesignId, "idx_design_versions_design");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DesignId).HasColumnName("design_id");
            entity.Property(e => e.FileUrl)
                .HasMaxLength(500)
                .HasColumnName("file_url");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.VersionNo).HasColumnName("version_no");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DesignVersions)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("design_versions_created_by_fkey");

            entity.HasOne(d => d.Design).WithMany(p => p.DesignVersions)
                .HasForeignKey(d => d.DesignId)
                .HasConstraintName("design_versions_design_id_fkey");
        });

        modelBuilder.Entity<DesignerProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("designer_profiles_pkey");

            entity.ToTable("designer_profiles");

            entity.HasIndex(e => e.ProviderId, "designer_profiles_provider_id_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DesignSpecialties)
                .HasMaxLength(255)
                .HasColumnName("design_specialties");
            entity.Property(e => e.DesignStyle)
                .HasMaxLength(150)
                .HasColumnName("design_style");
            entity.Property(e => e.MinProjectBudget)
                .HasPrecision(15, 2)
                .HasColumnName("min_project_budget");
            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.SoftwareSkills)
                .HasMaxLength(255)
                .HasColumnName("software_skills");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Provider).WithOne(p => p.DesignerProfile)
                .HasForeignKey<DesignerProfile>(d => d.ProviderId)
                .HasConstraintName("designer_profiles_provider_id_fkey");
        });

        modelBuilder.Entity<Handover>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("handovers_pkey");

            entity.ToTable("handovers");

            entity.HasIndex(e => e.ProjectId, "handovers_project_id_key").IsUnique();

            entity.HasIndex(e => e.ContractId, "idx_handovers_contract");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.ContractId).HasColumnName("contract_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentUrl)
                .HasMaxLength(500)
                .HasColumnName("document_url");
            entity.Property(e => e.HandoverDate).HasColumnName("handover_date");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");

            entity.HasOne(d => d.Contract).WithMany(p => p.Handovers)
                .HasForeignKey(d => d.ContractId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("handovers_contract_id_fkey");

            entity.HasOne(d => d.Project).WithOne(p => p.Handover)
                .HasForeignKey<Handover>(d => d.ProjectId)
                .HasConstraintName("handovers_project_id_fkey");
        });

        modelBuilder.Entity<HelpContent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("help_contents_pkey");

            entity.ToTable("help_contents");

            entity.HasIndex(e => e.CreatedBy, "idx_help_contents_creator");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Body).HasColumnName("body");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.HelpContents)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("help_contents_created_by_fkey");
        });

        modelBuilder.Entity<Inspection>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("inspections_pkey");

            entity.ToTable("inspections");

            entity.HasIndex(e => e.HireId, "idx_inspections_hire");

            entity.HasIndex(e => e.ProjectId, "idx_inspections_project");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.HireId).HasColumnName("hire_id");
            entity.Property(e => e.InspectedAt).HasColumnName("inspected_at");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");

            entity.HasOne(d => d.Hire).WithMany(p => p.Inspections)
                .HasForeignKey(d => d.HireId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("inspections_hire_id_fkey");

            entity.HasOne(d => d.Project).WithMany(p => p.Inspections)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("inspections_project_id_fkey");
        });

        modelBuilder.Entity<InspectionItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("inspection_items_pkey");

            entity.ToTable("inspection_items");

            entity.HasIndex(e => e.InspectionId, "idx_inspection_items_inspection");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.DefectNote).HasColumnName("defect_note");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.InspectionId).HasColumnName("inspection_id");
            entity.Property(e => e.IsPassed).HasColumnName("is_passed");

            entity.HasOne(d => d.Inspection).WithMany(p => p.InspectionItems)
                .HasForeignKey(d => d.InspectionId)
                .HasConstraintName("inspection_items_inspection_id_fkey");
        });

        modelBuilder.Entity<Issue>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("issues_pkey");

            entity.ToTable("issues");

            entity.HasIndex(e => e.HireId, "idx_issues_hire");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CostImpact)
                .HasPrecision(15, 2)
                .HasColumnName("cost_impact");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.HireId).HasColumnName("hire_id");
            entity.Property(e => e.ScheduleImpactDays).HasColumnName("schedule_impact_days");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Hire).WithMany(p => p.Issues)
                .HasForeignKey(d => d.HireId)
                .HasConstraintName("issues_hire_id_fkey");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("messages_pkey");

            entity.ToTable("messages");

            entity.HasIndex(e => e.ConversationId, "idx_messages_conversation");

            entity.HasIndex(e => e.SenderId, "idx_messages_sender");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Body)
                .IsRequired()
                .HasColumnName("body");
            entity.Property(e => e.ConversationId).HasColumnName("conversation_id");
            entity.Property(e => e.SenderId).HasColumnName("sender_id");
            entity.Property(e => e.SentAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("sent_at");

            entity.HasOne(d => d.Conversation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ConversationId)
                .HasConstraintName("messages_conversation_id_fkey");

            entity.HasOne(d => d.Sender).WithMany(p => p.Messages)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("messages_sender_id_fkey");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("notifications_pkey");

            entity.ToTable("notifications");

            entity.HasIndex(e => e.UserId, "idx_notifications_user");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.IsRead)
                .HasDefaultValue(false)
                .HasColumnName("is_read");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("notifications_user_id_fkey");
        });

        modelBuilder.Entity<OwnerProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("owner_profiles_pkey");

            entity.ToTable("owner_profiles");

            entity.HasIndex(e => e.UserId, "owner_profiles_user_id_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("full_name");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.ShopName)
                .HasMaxLength(200)
                .HasColumnName("shop_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithOne(p => p.OwnerProfile)
                .HasForeignKey<OwnerProfile>(d => d.UserId)
                .HasConstraintName("owner_profiles_user_id_fkey");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("permissions_pkey");

            entity.ToTable("permissions");

            entity.HasIndex(e => e.Code, "permissions_code_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("code");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
        });

        modelBuilder.Entity<PlatformFee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("platform_fees_pkey");

            entity.ToTable("platform_fees");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.Value)
                .HasPrecision(15, 2)
                .HasColumnName("value");
        });

        modelBuilder.Entity<PortfolioItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("portfolio_items_pkey");

            entity.ToTable("portfolio_items");

            entity.HasIndex(e => e.ProviderId, "idx_portfolio_items_provider");

            entity.HasIndex(e => e.ServiceTypeId, "idx_portfolio_items_type");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(500)
                .HasColumnName("image_url");
            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.ServiceTypeId).HasColumnName("service_type_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");

            entity.HasOne(d => d.Provider).WithMany(p => p.PortfolioItems)
                .HasForeignKey(d => d.ProviderId)
                .HasConstraintName("portfolio_items_provider_id_fkey");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.PortfolioItems)
                .HasForeignKey(d => d.ServiceTypeId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("portfolio_items_service_type_id_fkey");
        });

        modelBuilder.Entity<ProgressUpdate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("progress_updates_pkey");

            entity.ToTable("progress_updates");

            entity.HasIndex(e => e.HireId, "idx_progress_hire");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.HireId).HasColumnName("hire_id");
            entity.Property(e => e.Note).HasColumnName("note");
            entity.Property(e => e.Percent).HasColumnName("percent");
            entity.Property(e => e.UpdateDate).HasColumnName("update_date");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ProgressUpdates)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("progress_updates_created_by_fkey");

            entity.HasOne(d => d.Hire).WithMany(p => p.ProgressUpdates)
                .HasForeignKey(d => d.HireId)
                .HasConstraintName("progress_updates_hire_id_fkey");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("projects_pkey");

            entity.ToTable("projects");

            entity.HasIndex(e => e.OwnerId, "idx_projects_owner");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.AreaM2)
                .HasPrecision(10, 2)
                .HasColumnName("area_m2");
            entity.Property(e => e.Budget)
                .HasPrecision(15, 2)
                .HasColumnName("budget");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt).HasColumnName("deleted_at");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("name");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Owner).WithMany(p => p.Projects)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("projects_owner_id_fkey");
        });

        modelBuilder.Entity<ProjectHire>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("project_hires_pkey");

            entity.ToTable("project_hires");

            entity.HasIndex(e => e.BidId, "idx_hires_bid");

            entity.HasIndex(e => e.ProjectId, "idx_hires_project");

            entity.HasIndex(e => e.ProviderId, "idx_hires_provider");

            entity.HasIndex(e => e.ServiceTypeId, "idx_hires_type");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.BidId).HasColumnName("bid_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.RequestMessage).HasColumnName("request_message");
            entity.Property(e => e.ServiceTypeId).HasColumnName("service_type_id");
            entity.Property(e => e.StartedAt).HasColumnName("started_at");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Bid).WithMany(p => p.ProjectHires)
                .HasForeignKey(d => d.BidId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("project_hires_bid_id_fkey");

            entity.HasOne(d => d.Project).WithMany(p => p.ProjectHires)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("project_hires_project_id_fkey");

            entity.HasOne(d => d.Provider).WithMany(p => p.ProjectHires)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("project_hires_provider_id_fkey");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.ProjectHires)
                .HasForeignKey(d => d.ServiceTypeId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("project_hires_service_type_id_fkey");
        });

        modelBuilder.Entity<ProviderService>(entity =>
        {
            entity.HasKey(e => new { e.ProviderId, e.ServiceTypeId }).HasName("provider_services_pkey");

            entity.ToTable("provider_services");

            entity.HasIndex(e => e.ServiceTypeId, "idx_provider_services_type");

            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.ServiceTypeId).HasColumnName("service_type_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");

            entity.HasOne(d => d.Provider).WithMany(p => p.ProviderServices)
                .HasForeignKey(d => d.ProviderId)
                .HasConstraintName("provider_services_provider_id_fkey");

            entity.HasOne(d => d.ServiceType).WithMany(p => p.ProviderServices)
                .HasForeignKey(d => d.ServiceTypeId)
                .HasConstraintName("provider_services_service_type_id_fkey");
        });

        modelBuilder.Entity<Quotation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("quotations_pkey");

            entity.ToTable("quotations");

            entity.HasIndex(e => e.HireId, "idx_quotations_hire");

            entity.HasIndex(e => e.ProjectId, "idx_quotations_project");

            entity.HasIndex(e => e.ProviderId, "idx_quotations_provider");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.HireId).HasColumnName("hire_id");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.TotalAmount)
                .HasPrecision(15, 2)
                .HasColumnName("total_amount");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.ValidUntil).HasColumnName("valid_until");

            entity.HasOne(d => d.Hire).WithMany(p => p.Quotations)
                .HasForeignKey(d => d.HireId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("quotations_hire_id_fkey");

            entity.HasOne(d => d.Project).WithMany(p => p.Quotations)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("quotations_project_id_fkey");

            entity.HasOne(d => d.Provider).WithMany(p => p.Quotations)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("quotations_provider_id_fkey");
        });

        modelBuilder.Entity<QuotationItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("quotation_items_pkey");

            entity.ToTable("quotation_items");

            entity.HasIndex(e => e.QuotationId, "idx_quotation_items_quotation");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.LineTotal)
                .HasPrecision(15, 2)
                .HasColumnName("line_total");
            entity.Property(e => e.Quantity)
                .HasPrecision(12, 2)
                .HasColumnName("quantity");
            entity.Property(e => e.QuotationId).HasColumnName("quotation_id");
            entity.Property(e => e.Unit)
                .HasMaxLength(30)
                .HasColumnName("unit");
            entity.Property(e => e.UnitPrice)
                .HasPrecision(15, 2)
                .HasColumnName("unit_price");

            entity.HasOne(d => d.Quotation).WithMany(p => p.QuotationItems)
                .HasForeignKey(d => d.QuotationId)
                .HasConstraintName("quotation_items_quotation_id_fkey");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("reviews_pkey");

            entity.ToTable("reviews");

            entity.HasIndex(e => e.OwnerId, "idx_reviews_owner");

            entity.HasIndex(e => e.ProjectId, "idx_reviews_project");

            entity.HasIndex(e => e.ProviderId, "idx_reviews_provider");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.OverallRating)
                .HasPrecision(3, 2)
                .HasColumnName("overall_rating");
            entity.Property(e => e.OwnerId).HasColumnName("owner_id");
            entity.Property(e => e.ProjectId).HasColumnName("project_id");
            entity.Property(e => e.ProviderId).HasColumnName("provider_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Owner).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("reviews_owner_id_fkey");

            entity.HasOne(d => d.Project).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("reviews_project_id_fkey");

            entity.HasOne(d => d.Provider).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("reviews_provider_id_fkey");
        });

        modelBuilder.Entity<ReviewScore>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("review_scores_pkey");

            entity.ToTable("review_scores");

            entity.HasIndex(e => e.ReviewId, "idx_review_scores_review");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Dimension)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("dimension");
            entity.Property(e => e.ReviewId).HasColumnName("review_id");
            entity.Property(e => e.Score).HasColumnName("score");

            entity.HasOne(d => d.Review).WithMany(p => p.ReviewScores)
                .HasForeignKey(d => d.ReviewId)
                .HasConstraintName("review_scores_review_id_fkey");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("roles_pkey");

            entity.ToTable("roles");

            entity.HasIndex(e => e.Name, "roles_name_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");

            entity.HasMany(d => d.Permissions).WithMany(p => p.Roles)
                .UsingEntity<Dictionary<string, object>>(
                    "RolePermission",
                    r => r.HasOne<Permission>().WithMany()
                        .HasForeignKey("PermissionId")
                        .HasConstraintName("role_permissions_permission_id_fkey"),
                    l => l.HasOne<Role>().WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("role_permissions_role_id_fkey"),
                    j =>
                    {
                        j.HasKey("RoleId", "PermissionId").HasName("role_permissions_pkey");
                        j.ToTable("role_permissions");
                        j.HasIndex(new[] { "PermissionId" }, "idx_role_permissions_perm");
                        j.IndexerProperty<long>("RoleId").HasColumnName("role_id");
                        j.IndexerProperty<long>("PermissionId").HasColumnName("permission_id");
                    });
        });

        modelBuilder.Entity<ServiceProvider>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("service_providers_pkey");

            entity.ToTable("service_providers");

            entity.HasIndex(e => e.UserId, "service_providers_user_id_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.AvgRating)
                .HasPrecision(3, 2)
                .HasColumnName("avg_rating");
            entity.Property(e => e.Bio).HasColumnName("bio");
            entity.Property(e => e.CompanyTaxCode)
                .HasMaxLength(50)
                .HasColumnName("company_tax_code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt).HasColumnName("deleted_at");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("display_name");
            entity.Property(e => e.IsVerified)
                .HasDefaultValue(false)
                .HasColumnName("is_verified");
            entity.Property(e => e.PortfolioHeadline)
                .HasMaxLength(200)
                .HasColumnName("portfolio_headline");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.YearsExperience).HasColumnName("years_experience");

            entity.HasOne(d => d.User).WithOne(p => p.ServiceProvider)
                .HasForeignKey<ServiceProvider>(d => d.UserId)
                .HasConstraintName("service_providers_user_id_fkey");
        });

        modelBuilder.Entity<ServiceType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("service_types_pkey");

            entity.ToTable("service_types");

            entity.HasIndex(e => e.Code, "service_types_code_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("code");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Survey>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("surveys_pkey");

            entity.ToTable("surveys");

            entity.HasIndex(e => e.HireId, "idx_surveys_hire");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.ConditionNote).HasColumnName("condition_note");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.HireId).HasColumnName("hire_id");
            entity.Property(e => e.ReportUrl)
                .HasMaxLength(500)
                .HasColumnName("report_url");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.Version)
                .HasDefaultValue(1)
                .HasColumnName("version");

            entity.HasOne(d => d.Hire).WithMany(p => p.Surveys)
                .HasForeignKey(d => d.HireId)
                .HasConstraintName("surveys_hire_id_fkey");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("users_pkey");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "users_email_key").IsUnique();

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DeletedAt).HasColumnName("deleted_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.EmailVerifiedAt).HasColumnName("email_verified_at");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId }).HasName("user_roles_pkey");

            entity.ToTable("user_roles");

            entity.HasIndex(e => e.RoleId, "idx_user_roles_role");

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("user_roles_role_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("user_roles_user_id_fkey");
        });

        modelBuilder.Entity<Warranty>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("warranties_pkey");

            entity.ToTable("warranties");

            entity.HasIndex(e => e.HandoverId, "idx_warranties_handover");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.HandoverId).HasColumnName("handover_id");
            entity.Property(e => e.Scope)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("scope");
            entity.Property(e => e.StartDate).HasColumnName("start_date");

            entity.HasOne(d => d.Handover).WithMany(p => p.Warranties)
                .HasForeignKey(d => d.HandoverId)
                .HasConstraintName("warranties_handover_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}