// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartCoffeeBuilder.Repository.Models;

public partial class Survey
{
    public long Id { get; set; }

    public long HireId { get; set; }

    public int Version { get; set; }

    public string ConditionNote { get; set; }

    public string ReportUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ProjectHire Hire { get; set; }
}