// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCoffeeBuilder.Repository.DBContext;

#nullable disable

namespace SmartCoffeeBuilder.Repository.Migrations
{
    [DbContext(typeof(SmartCafeBuilderContext))]
    [Migration("20260709155540_MapProviderStatusToV5")]
    partial class MapProviderStatusToV5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.AiRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("BriefId")
                        .HasColumnType("bigint")
                        .HasColumnName("brief_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConceptSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concept_summary");

                    b.Property<decimal?>("ContingencyPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("contingency_percent");

                    b.Property<string>("CostNotes")
                        .HasColumnType("text")
                        .HasColumnName("cost_notes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerFlow")
                        .HasColumnType("jsonb")
                        .HasColumnName("customer_flow");

                    b.Property<decimal?>("EquipmentMaxVnd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("equipment_max_vnd");

                    b.Property<decimal?>("EquipmentMinVnd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("equipment_min_vnd");

                    b.Property<decimal?>("EstimatedConstructionCost")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("estimated_construction_cost");

                    b.Property<decimal?>("EstimatedDesignCost")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("estimated_design_cost");

                    b.Property<decimal?>("FitoutMaxVnd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fitout_max_vnd");

                    b.Property<decimal?>("FitoutMinVnd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fitout_min_vnd");

                    b.Property<string>("ImageArtifactUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_artifact_url");

                    b.Property<string>("ImageAspectRatio")
                        .HasColumnType("text")
                        .HasColumnName("image_aspect_ratio");

                    b.Property<string>("ImageNegativePrompt")
                        .HasColumnType("text")
                        .HasColumnName("image_negative_prompt");

                    b.Property<string>("ImagePrompt")
                        .HasColumnType("text")
                        .HasColumnName("image_prompt");

                    b.Property<string>("ImageReferenceUrls")
                        .HasColumnType("jsonb")
                        .HasColumnName("image_reference_urls");

                    b.Property<string>("ImageView")
                        .HasColumnType("text")
                        .HasColumnName("image_view");

                    b.Property<string>("JobId")
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("LayoutAdjacencyRules")
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_adjacency_rules");

                    b.Property<double?>("LayoutHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("layout_height");

                    b.Property<string>("LayoutUnit")
                        .HasColumnType("text")
                        .HasColumnName("layout_unit");

                    b.Property<double?>("LayoutWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("layout_width");

                    b.Property<string>("LayoutZones")
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_zones");

                    b.Property<string>("ParentJobId")
                        .HasColumnType("text")
                        .HasColumnName("parent_job_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("PlanConceptName")
                        .HasColumnType("text")
                        .HasColumnName("plan_concept_name");

                    b.Property<string>("PlanJson")
                        .HasColumnType("text")
                        .HasColumnName("plan_json");

                    b.Property<string>("PlanSummary")
                        .HasColumnType("text")
                        .HasColumnName("plan_summary");

                    b.Property<string>("Recommendations")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.Property<string>("RiskNotes")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_notes");

                    b.Property<int?>("SeatCapacityRecommendation")
                        .HasColumnType("integer")
                        .HasColumnName("seat_capacity_recommendation");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_ai_recommendations");

                    b.HasIndex("BriefId")
                        .HasDatabaseName("ix_ai_recommendations_brief_id");

                    b.ToTable("ai_recommendations", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.BudgetItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ActualAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("actual_amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("PlannedAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("planned_amount");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_budget_items");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_budget_items_project_id");

                    b.ToTable("budget_items", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ConstructionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date")
                        .HasColumnName("actual_at");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EstimateAt")
                        .HasColumnType("date")
                        .HasColumnName("estimate_at");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_done");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_construction_items");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_construction_items_created_by");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_construction_items_parent_id");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_construction_items_project_provider_id");

                    b.ToTable("construction_items", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ConstructorProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("LicenseNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_no");

                    b.Property<decimal?>("MaxProjectValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("max_project_value");

                    b.Property<long>("ProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_id");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("team_size");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WarrantyPolicy")
                        .HasColumnType("text")
                        .HasColumnName("warranty_policy");

                    b.HasKey("Id")
                        .HasName("pk_constructor_profiles");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasDatabaseName("ix_constructor_profiles_provider_id");

                    b.ToTable("constructor_profiles", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AgreedValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("agreed_value");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<long?>("ConfirmedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("document_url");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expires_at");

                    b.Property<string>("PartyInfo")
                        .HasColumnType("text")
                        .HasColumnName("party_info");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Terms")
                        .HasColumnType("text")
                        .HasColumnName("terms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ConfirmedBy")
                        .HasDatabaseName("ix_contracts_confirmed_by");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_contracts_project_provider_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_conversations_project_provider_id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Design", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Version")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_designs");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_designs_created_by");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_designs_project_provider_id");

                    b.ToTable("designs", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DesignBrief", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BrandNote")
                        .HasColumnType("text")
                        .HasColumnName("brand_note");

                    b.Property<string>("BusinessGoals")
                        .HasColumnType("text")
                        .HasColumnName("business_goals");

                    b.Property<string>("BusinessModel")
                        .HasColumnType("text")
                        .HasColumnName("business_model");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mood");

                    b.Property<string>("OperationNote")
                        .HasColumnType("text")
                        .HasColumnName("operation_note");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<int?>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("style");

                    b.Property<string>("TargetCustomer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_customer");

                    b.Property<string>("Timeline")
                        .HasColumnType("text")
                        .HasColumnName("timeline");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_design_briefs");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_design_briefs_project_id");

                    b.ToTable("design_briefs", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DesignImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DesignId")
                        .HasColumnType("bigint")
                        .HasColumnName("design_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_design_images");

                    b.HasIndex("DesignId")
                        .HasDatabaseName("ix_design_images_design_id");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_design_images_uploaded_by");

                    b.ToTable("design_images", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DesignerProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DesignStyle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("design_style");

                    b.Property<decimal?>("MinProjectBudget")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("min_project_budget");

                    b.Property<long>("ProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_id");

                    b.Property<string>("SoftwareSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("software_skills");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialties");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_designer_profiles");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasDatabaseName("ix_designer_profiles_provider_id");

                    b.ToTable("designer_profiles", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Doc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DocTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("doc_type_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_docs");

                    b.HasIndex("DocTypeId")
                        .HasDatabaseName("ix_docs_doc_type_id");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_docs_project_provider_id");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_docs_uploaded_by");

                    b.ToTable("docs", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DocType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_doc_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_doc_types_code");

                    b.ToTable("doc_types", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("ActualAt")
                        .HasColumnType("date")
                        .HasColumnName("actual_at");

                    b.Property<string>("Cause")
                        .HasColumnType("text")
                        .HasColumnName("cause");

                    b.Property<string>("ConfirmImage")
                        .HasColumnType("text")
                        .HasColumnName("confirm_image");

                    b.Property<long?>("ConstructionItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("construction_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EstimateAt")
                        .HasColumnType("date")
                        .HasColumnName("estimate_at");

                    b.Property<string>("IssueImage")
                        .HasColumnType("text")
                        .HasColumnName("issue_image");

                    b.Property<long>("IssueTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_type_id");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("ConstructionItemId")
                        .HasDatabaseName("ix_issues_construction_item_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_issues_created_by");

                    b.HasIndex("IssueTypeId")
                        .HasDatabaseName("ix_issues_issue_type_id");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_issues_project_provider_id");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.IssueType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_issue_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_types_code");

                    b.ToTable("issue_types", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversation_id");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_notifications_account_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Otp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CodeRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("code_refreshed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("current_code");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("PreviousCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("previous_code");

                    b.HasKey("Id")
                        .HasName("pk_otps");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_otps_account_id");

                    b.ToTable("otps", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<decimal>("AreaM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("area_m2");

                    b.Property<decimal>("Budget")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("budget");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EstimatedDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_days");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint")
                        .HasColumnName("post_id");

                    b.Property<string>("Proposal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proposal");

                    b.Property<long>("ProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_project_applications");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_project_applications_post_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_project_applications_provider_id");

                    b.ToTable("project_applications", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("ServiceKind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("service_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmissionDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_deadline");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_project_posts");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_posts_project_id");

                    b.ToTable("project_posts", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contract_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("ProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("provider_id");

                    b.Property<string>("RequestMessage")
                        .HasColumnType("text")
                        .HasColumnName("request_message");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_project_providers");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_project_providers_application_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_providers_project_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_project_providers_provider_id");

                    b.ToTable("project_providers", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_refresh_tokens_account_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("OverallRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("overall_rating");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_reviews_project_provider_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ReviewScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dimension");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_review_scores");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_review_scores_review_id");

                    b.ToTable("review_scores", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ServiceProvider", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<decimal>("AvgRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("avg_rating");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("capability");

                    b.Property<string>("CompanyTaxCode")
                        .HasColumnType("text")
                        .HasColumnName("company_tax_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PortfolioHeadline")
                        .HasColumnType("text")
                        .HasColumnName("portfolio_headline");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_experience");

                    b.HasKey("Id")
                        .HasName("pk_service_providers");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_providers_account_id");

                    b.ToTable("service_providers", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ShopOwner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shop_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_shop_owners");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_owners_account_id");

                    b.ToTable("shop_owners", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Survey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConditionNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_note");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<long>("ProjectProviderId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_provider_id");

                    b.Property<string>("ReportUrl")
                        .HasColumnType("text")
                        .HasColumnName("report_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Version")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_surveys");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_surveys_created_by");

                    b.HasIndex("ProjectProviderId")
                        .HasDatabaseName("ix_surveys_project_provider_id");

                    b.ToTable("surveys", (string)null);
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.AiRecommendation", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.DesignBrief", "Brief")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("BriefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_recommendations_design_briefs_brief_id");

                    b.Navigation("Brief");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.BudgetItem", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Project", "Project")
                        .WithMany("BudgetItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_items_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ConstructionItem", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_construction_items_accounts_created_by");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ConstructionItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_construction_items_construction_items_parent_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("ConstructionItems")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_construction_items_project_providers_project_provider_id");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Parent");

                    b.Navigation("ProjectProvider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ConstructorProfile", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ServiceProvider", "Provider")
                        .WithOne("ConstructorProfile")
                        .HasForeignKey("SmartCoffeeBuilder.Repository.Models.ConstructorProfile", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_constructor_profiles_service_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Contract", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "ConfirmedByAccount")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contracts_accounts_confirmed_by");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("Contracts")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_project_providers_project_provider_id");

                    b.Navigation("ConfirmedByAccount");

                    b.Navigation("ProjectProvider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Conversation", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("Conversations")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_project_providers_project_provider_id");

                    b.Navigation("ProjectProvider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Design", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_designs_accounts_created_by");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("Designs")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_designs_project_providers_project_provider_id");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("ProjectProvider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DesignBrief", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Project", "Project")
                        .WithOne("DesignBrief")
                        .HasForeignKey("SmartCoffeeBuilder.Repository.Models.DesignBrief", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_design_briefs_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DesignImage", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Design", "Design")
                        .WithMany("DesignImages")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_design_images_designs_design_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "UploadedByAccount")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_design_images_accounts_uploaded_by");

                    b.Navigation("Design");

                    b.Navigation("UploadedByAccount");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DesignerProfile", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ServiceProvider", "Provider")
                        .WithOne("DesignerProfile")
                        .HasForeignKey("SmartCoffeeBuilder.Repository.Models.DesignerProfile", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_designer_profiles_service_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Doc", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.DocType", "DocType")
                        .WithMany("Docs")
                        .HasForeignKey("DocTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_docs_doc_types_doc_type_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("Docs")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_docs_project_providers_project_provider_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "UploadedByAccount")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_docs_accounts_uploaded_by");

                    b.Navigation("DocType");

                    b.Navigation("ProjectProvider");

                    b.Navigation("UploadedByAccount");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Issue", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ConstructionItem", "ConstructionItem")
                        .WithMany("Issues")
                        .HasForeignKey("ConstructionItemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_issues_construction_items_construction_item_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_issues_accounts_created_by");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.IssueType", "IssueType")
                        .WithMany("Issues")
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_issue_types_issue_type_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_project_providers_project_provider_id");

                    b.Navigation("ConstructionItem");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("IssueType");

                    b.Navigation("ProjectProvider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Message", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_accounts_sender_id");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Notification", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Otp", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "Account")
                        .WithMany("Otps")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otps_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Project", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ShopOwner", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_shop_owners_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectApplication", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectPost", "Post")
                        .WithMany("ProjectApplications")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_applications_project_posts_post_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ServiceProvider", "Provider")
                        .WithMany("ProjectApplications")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_applications_service_providers_provider_id");

                    b.Navigation("Post");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectPost", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Project", "Project")
                        .WithMany("ProjectPosts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_posts_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectProvider", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectApplication", "Application")
                        .WithMany("ProjectProviders")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_providers_project_applications_application_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Project", "Project")
                        .WithMany("ProjectProviders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_providers_projects_project_id");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ServiceProvider", "Provider")
                        .WithMany("ProjectProviders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_providers_service_providers_provider_id");

                    b.Navigation("Application");

                    b.Navigation("Project");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.RefreshToken", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Review", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("Reviews")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_project_providers_project_provider_id");

                    b.Navigation("ProjectProvider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ReviewScore", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Review", "Review")
                        .WithMany("ReviewScores")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_scores_reviews_review_id");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ServiceProvider", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "Account")
                        .WithOne("ServiceProvider")
                        .HasForeignKey("SmartCoffeeBuilder.Repository.Models.ServiceProvider", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_providers_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ShopOwner", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "Account")
                        .WithOne("ShopOwner")
                        .HasForeignKey("SmartCoffeeBuilder.Repository.Models.ShopOwner", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_owners_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Survey", b =>
                {
                    b.HasOne("SmartCoffeeBuilder.Repository.Models.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_surveys_accounts_created_by");

                    b.HasOne("SmartCoffeeBuilder.Repository.Models.ProjectProvider", "ProjectProvider")
                        .WithMany("Surveys")
                        .HasForeignKey("ProjectProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveys_project_providers_project_provider_id");

                    b.Navigation("CreatedByAccount");

                    b.Navigation("ProjectProvider");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Account", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Otps");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ServiceProvider");

                    b.Navigation("ShopOwner");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ConstructionItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Issues");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Design", b =>
                {
                    b.Navigation("DesignImages");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DesignBrief", b =>
                {
                    b.Navigation("AiRecommendations");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.DocType", b =>
                {
                    b.Navigation("Docs");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.IssueType", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Project", b =>
                {
                    b.Navigation("BudgetItems");

                    b.Navigation("DesignBrief");

                    b.Navigation("ProjectPosts");

                    b.Navigation("ProjectProviders");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectApplication", b =>
                {
                    b.Navigation("ProjectProviders");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectPost", b =>
                {
                    b.Navigation("ProjectApplications");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ProjectProvider", b =>
                {
                    b.Navigation("ConstructionItems");

                    b.Navigation("Contracts");

                    b.Navigation("Conversations");

                    b.Navigation("Designs");

                    b.Navigation("Docs");

                    b.Navigation("Issues");

                    b.Navigation("Reviews");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Review", b =>
                {
                    b.Navigation("ReviewScores");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ServiceProvider", b =>
                {
                    b.Navigation("ConstructorProfile");

                    b.Navigation("DesignerProfile");

                    b.Navigation("ProjectApplications");

                    b.Navigation("ProjectProviders");
                });

            modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.ShopOwner", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
