// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCoffeeBuilder.Repository.DBContext;

#nullable disable

namespace SmartCoffeeBuilder.Repository.Migrations
{
    [DbContext(typeof(SmartCafeBuilderContext))]
    [Migration("20260808193000_AddCommentsAndDesignVersions")]
    partial class AddCommentsAndDesignVersions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Designer file này chỉ cần tồn tại để EF Core nhận diện migration.
            // ModelSnapshot đầy đủ nằm ở SmartCafeBuilderContextModelSnapshot.cs
            // (sẽ được cập nhật khi chạy `dotnet ef migrations add` ở máy có dotnet CLI).
            _ = modelBuilder.Entity("SmartCoffeeBuilder.Repository.Models.Account");
        }
    }
}